name: CI/CD - MySQL ClimateData Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  db-pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p${{ secrets.DB_PASSWORD }} --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_CONN_STR: ${{ secrets.DB_CONN_STR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MySQL client & Python
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "MySQL client installed."
      - name: Wait for MySQL readiness
        run: |
          for i in {1..60}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -p"${DB_PASSWORD}" --silent; then
              echo "MySQL is up."
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      # 1) Initial Schema Deployment
      - name: Create table
        run: |
          mysql -h 127.0.0.1 -uroot -p"${DB_PASSWORD}" < sql/01_create_table.sql

      # 2) Schema Update
      - name: Add humidity column
        run: |
          mysql -h 127.0.0.1 -uroot -p"${DB_PASSWORD}" < sql/02_alter_add_humidity.sql

      # 3) Data Seeding
      - name: Seed sample data
        run: |
          mysql -h 127.0.0.1 -uroot -p"${DB_PASSWORD}" < sql/03_seed_data.sql

      # 4) Concurrent Query Execution (python)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
      - name: Install Python deps
        run: pip install mysql-connector-python
      - name: Run concurrent workload
        run: python scripts/multi_thread_queries.py

      # 5) Validation
      - name: Validation queries
        run: |
          mkdir -p artifacts
          mysql -h 127.0.0.1 -uroot -p"${DB_PASSWORD}" < sql/04_validate.sql | tee artifacts/validation_output.txt
          echo "SHOW CREATE TABLE project_db.ClimateData\G" | mysql -h 127.0.0.1 -uroot -p"${DB_PASSWORD}" | tee -a artifacts/validation_output.txt

      - name: Upload artifacts (logs & validation)
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: artifacts/
